### ISSUE TITLE
Multiple Buildpack Support

### ISSUE THREAD

**Issue by sclevine** [cloudfoundry/docs-buildpacks#148]
Hi Docs Team,

Support for applying multiple buildpacks to a single application is arriving in CF soon.

I put together a doc that describes the buildpack and app developer changes: https://docs.google.com/a/pivotal.io/document/d/1yA3Ltc3rnW7LPsZovsA3BlLVF36stFgSKlXLLdM3xek/edit?usp=sharing

What's the best way to integrate these changes into the buildpack docs?

Thanks,
Stephen
(Core Buildpacks PM)

**Comment by thewoolleyman** [comment]
Here are some suggestions I have after trying to use this based on the info in the doc Stephen attached, which is good, but rather dense and requires some prior context to understand.

In addition to documentation for this, it would be very helpful to have a very simple "barebones" example buildpack(s), that illustrated how the contracts of the `supply` and `finalize` scripts should be implemented.

When I initially looked into it, I was a bit confused on the required ordering/usage of the various directories and indexes, as well as other implementation details, and a simple working example would have helped a lot.  This is very helpful for the type of people who like to learn by looking at existing code.

I tried looking at existing examples which have already been converted (ruby, go, staticfile), but they are so abstracted that it's difficult to really follow what is going on.  Even the staticfile `supply` and `finalize` just installs `go` and hands it off all the params to another script to do the work.

One idea for a simple example could just be a minimal bash-only buildpacks which is intended to be run twice, after after the staticfile buildpack, with dummy behavior to only add some additional content to be served (possibly controlled by env vars), and illustrate intended usage of the 'supply' and 'finalize' scripts.

Also, it would be good to perhaps have a summary in the docs that makes clear the differences in the implementation between this and heroku's multi-buildpack support, and the challenges to expect if you are trying to convert or reimplement an existing heroku buildpack which supports multi-buildpack (e.g. [1] and [2]).

It can be confusing, because there's much more incompatibility between heroku and cf in the multi-buildpack scenario than in the traditional single-buildpack scenario.  One example: the first two positional arguments to the scripts are the same, but the third and fourth are different - which makes it more technically challenging to "retrofit" an existing open-source heroku buildpack to support both CF and heroku.

Or, even if you don't explicitly explain the differences, at least make a mention that the contracts are different, and one shouldn't necessarily expect a conversion or retrofit to be straightforward.

Thanks,
-- Chad

[1] https://github.com/HashNuke/heroku-buildpack-elixir
[2] https://github.com/gjaldon/heroku-buildpack-phoenix-static
