### ISSUE TITLE
buildpack for pure kotlin-based web project

### ISSUE THREAD

**Issue by nykykof** [cloudfoundry/docs-buildpacks#210]
Hello
I'm working on a pure kotlin-based web project. Everything is fine localy and with my CI pipeline also. The issue comes when i want to push the project on Cloud Foundry: The official java buildpack does not work for the project.
Is there a dedicated buildpack for kotlin projects or some java buildpack version which works with kotlin project ?

**Comment by nebhale** [comment]
The Java Buildpack will run compiled Kotlin code as long as it meets one of the [container detection criteria](https://github.com/cloudfoundry/java-buildpack#additional-documentation) (typically Java `main()`).  We know this because the Spring team regularly runs this type of application.

If you'd like to run something that we don't yet support (a container-style that Kotlin prefers, maybe from source if that's a thing), then you should open an [issue](https://github.com/cloudfoundry/java-buildpack/issues) and we will look at it.

**Comment by bentarnoff** [comment]
@nykykof Closing this issue. Thanks.
