### ISSUE TITLE
Python 3.5.1 not found

### ISSUE THREAD

**Issue by addisonhuddy** [cloudfoundry/docs-buildpacks#50]
I'm pushing a bottle app to PWS but I'm running to an issue.  

Inside `runtime.txt` I've specified `python-3.5.1` and it looks like the buildpack picks that up, but CF can't find 3.5.1.  Is this not yet a supported version on PWS?
```
Install Python.
-----> Found python-2.7.11, removing.
-----> Preparing Python runtime (python-3.5.1.)
 !     Requested runtime (python-3.5.1.) was not found.
```

**Comment by davidjahn** [comment]
Hi @addisonhuddy, 3.5.1 [should be supported](https://github.com/cloudfoundry/python-buildpack/releases) by the latest buildpack.

I just tried to `cf push` a [sample flask app](https://github.com/cloudfoundry/python-buildpack/tree/master/cf_spec/fixtures/flask_web_app_python_3) on PWS with the `runtime.txt` modified to contain `python-3.5.1` and it worked. If you could give a sample app that replicates your issue it would be very helpful.

Are you possibly specifying the URL of an older python-buildpack in your app's `manifest.yml` file?

ps: usually the best place to start an issue about python apps is in on the [python-buildpack repo](https://github.com/cloudfoundry/python-buildpack/) rather than here, which is the repo for the buildpack documentation website on cloudfoundry.org

**Comment by Dannyzen** [comment]
@addisonhuddy is this still an issue? The Buildpacks team is happy to help. If so please open a new issue under https://github.com/cloudfoundry/python-buildpack/issues

**Comment by addisonhuddy** [comment]
I still haven't been able to get it to work, but I suspect it is my app. Closing the issue.
